// <auto-generated />
namespace ShaulisBlog.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _2810161013 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2810161013));
        
        string IMigrationMetadata.Id
        {
            get { return "201610280713268_2810161013"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
